apiVersion: v1
kind: ConfigMap
metadata:
  name: handmade-config
data:
  application.yml: |
    spring:
      application:
        name: handmade-service
      datasource:
        url: jdbc:postgresql://postgres:5432/handmade
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
      redis:
        host: redis
        port: 6379
    server:
      port: 8080
    logging:
      level:
        root: INFO
        com.handmade.ecommerce: INFO
