apiVersion: apps/v1
kind: Deployment
metadata:
  name: handmade-service
  labels:
    app: handmade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: handmade-service
  template:
    metadata:
      labels:
        app: handmade-service
    spec:
      containers:
        - name: handmade-service
          image: handmade-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
