apiVersion: apps/v1
kind: Deployment
metadata:
  name: handmade-service
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: handmade-service
        environment: production
    spec:
      containers:
        - name: handmade-service
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_OPTS
              value: "-Xmx2g -Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
            # Redis configuration
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: handmade-config
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: handmade-config
                  key: redis_port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: handmade-secrets
                  key: redis_password
            # RabbitMQ configuration
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: handmade-config
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: handmade-config
                  key: rabbitmq_port
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: handmade-config
                  key: rabbitmq_username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: handmade-secrets
                  key: rabbitmq_password
            # Database configuration
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: handmade-config
                  key: db_url
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: handmade-config
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: handmade-secrets
                  key: db_password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - handmade-service
                topologyKey: kubernetes.io/hostname
