apiVersion: v1
kind: ConfigMap
metadata:
  name: handmade-config
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres-sit:5432/handmade_sit
      jpa:
        show-sql: false
    logging:
      level:
        root: INFO
        com.handmade.ecommerce: INFO
