apiVersion: apps/v1
kind: Deployment
metadata:
  name: handmade-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: handmade-service
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod-local"
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
